### ISSUE TITLE
I didn't understand it well

### ISSUE THREAD

**Issue by geaplanet** [dop251/diskrsync#1]
I cloned several 32Gb pendrives with a linux system installed and I modified one of them ("the master") with some little programs and files. Can I use diskrsync for re-clone pendrives coping only the differents blocks?

**Comment by dop251** [comment]
After this command:

```
diskrsync --nocompress source target
```

target should be identical to the source.

**Comment by geaplanet** [comment]
Thanks a lot! It is exactly what I was looking for. Yes, all pendrives are identical. Just out of curiosity, if the target is bigger, would it work too?

**Comment by dop251** [comment]
It will try to truncate the target if it's bigger which works for files, but obviously not for devices. Bear in mind the main purpose of this tool is backup.
