### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by grinapo** [dop251/diskrsync#13]
It would be neat to include in readme something like this for noobs like me (since you've already told how to pull the golang environment and the repo):

> To rebuild the code try:

    cd src/github.com/dop251/diskrsync
    go build -o /tmp/diskrsync diskrsync/main.go

**Comment by dop251** [comment]
The build instructions are for someone who doesn't know anything about Go, but would like to use the program. If a person is going to do code changes it's reasonable to assume they have invested some time into learning about Go.

BTW, a better command would be ```go install ./diskrsync```

**Comment by grinapo** [comment]
I accept your decision not to include **two additional lines** into the readme. ;-) 

(Background: the "some time invested" usually does not involve an empty root project directory with lots of external directories, I had to trial-and-error where the build shall be started.)
