### ISSUE TITLE
Can diskrsync write to a zfs volume ?

### ISSUE THREAD

**Issue by ierdnah** [dop251/diskrsync#14]
Hi,

I try to move a qcow2 disk image over the network to a zvol (zfs volume).
I've attached the qcow2 file to nbd0 on the remote server and then on the local server:
`diskrsync --ssh-flags="-p22" --verbose --no-compress root@x.x.x.x:/dev/nbd0 /dev/zvol/vm-storage/vm-100-disk1`
The program does not transmit bulk the data over the network.
On the remote node (the one with qcow2) a strace shows some futex and resource unavailable.
Should I wait more or this mode of writing directly to a block device is not supported ?

**Comment by dop251** [comment]
It is supported.

**Comment by ierdnah** [comment]
It took a little longer until it started but it works. Thank you !
