### ISSUE TITLE
Connection stalled detection

### ISSUE THREAD

**Issue by Evengard** [dop251/diskrsync#16]
Sometimes when the internet goes wonky, the underlying SSH connection gets stalled, which results in 0 transfer speed. At this stage, the transfer seems to be stuck because of the underlying SSH client actually not understanding what is happening, and ConnectTimeout doesn't actually seem to help on an already established SSH connection.

It would be nice, if diskrsync would be able to automatically detect such conditions, terminate ssh and restart the transfer automatically (probably rechecking both the source and the target to find out from where it needs to resume the transfer again).

**Comment by grinapo** [comment]
Or simply timeout and die. Doesn't it?

**Comment by dop251** [comment]
Transport errors (including stalling) should be detected and handled at the transport level, not at the application level, in my opinion. In this particular case, SSH should set TCP keepalive timeout which should eventually kill the connection.
