### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Evengard** [dop251/diskrsync#18]
It would be nice if diskrsync would allow to copy from Windows hosts as well, by using the `\\.\PHYSICALDRIVE0` or `\\?\Volume{guid}` paths for the actual block devices.

I've actually checked (attempted to compile it under Windows and run it - it almost worked), and the default Golang file APIs allows to open such devices, even though it would be best to also call a Windows-specific API to get the minimum allowed buffer size for actually reading such devices. Also the paths with the reversed slashes seems to not work too well.

Now, this one actually depends on #17 because calling from Windows implies having `.exe` in a path, and we can't have that on the target Linux box.

**Comment by dop251** [comment]
I don't have a Windows environment and don't have any interest in Windows in general. #17 is now fixed, if there is anything else missing, I would welcome PRs.
