### ISSUE TITLE
cannot use path@version syntax in GOPATH mode

### ISSUE THREAD

**Issue by Steve-Newcomb** [dop251/diskrsync#21]
Following the usage instructions doesn't work for me.  I'm using Debian 11.

```
221024 11:22 /usr/local/ch-tools3/GO root@piglet{2}# GOPATH=$(pwd) go install github.com/dop251/diskrsync/diskrsync@latest
package github.com/dop251/diskrsync/diskrsync@latest: cannot use path@version syntax in GOPATH mode

```

**Comment by dop251** [comment]
Debian 11 has go 1.15, but minimum required (as stated in the README) is 1.16. Please try using 1.19 from backports: https://packages.debian.org/bullseye-backports/golang-go

**Comment by grinapo** [comment]
@dop251 you should close resolved issues so github won't show "8 open issues" in the header, while in reality most of them are non-issues. :wink:
