### ISSUE TITLE
Target failed: target: while copying block: file too large

### ISSUE THREAD

**Issue by zjuchenyuan** [dop251/diskrsync#23]
I'm baking up a 21.8 TB disk using diskrsync, to a remote server with ext4

```
Sync  16.00 TiB / 21.83 TiB [=============================================================>                      ]  73 %
2023/02/01 23:08:25 Target failed: target: while copying block: file too large
2023/02/01 23:08:25 Read: 16, wrote: 14753557643280
2023/02/01 23:08:25 target error: exit status 1
```

I found that ext4's limit for a single file is 16TB, could you add a walkaround for this limit? Like dividing to multiple target files.

I want to continue this backup, without copying this 16TB data again.

Thanks

**Comment by dop251** [comment]
It's a lot of effort and I don't think the result would justify it. It should be easy enough to switch from ext4 to any other filesystem that does not have this limitation. For backups CoW filesystems such as btrfs or zfs are particularly useful because of snapshots.
