### ISSUE TITLE
This repo still active?

### ISSUE THREAD

**Issue by awels** [dop251/diskrsync#24]
Hi just wondering if this is still active and if you are taking requests and PRs?

In particular I would like to add TLS connectivity besides ssh if that is possible.

**Comment by dop251** [comment]
Yes, however I don't think adding TLS would be a good idea. I deliberately left transport (including authentication, encryption, compression, etc.) out of the scope. SSH is ubiquitous, reliable, and does all this very well. 

Neither would it be a trivial task, considering it uses stdin/stdout for main traffic and stderr for progress bar.

**Comment by awels** [comment]
So I am trying to integrate this with a kubernetes project called volsync, which is standardizing on TLS (instead of ssh) and we will have a source and target process running, so I don't need ssh to start the receiving process for instance. If you are taking PRs I will probably take a stab at it.

**Comment by dop251** [comment]
Strictly speaking the synchronisation code itself is transport-agnostic. You could use it as a library (`diskrsync.Source()` and `diskrsync.Target()`) without modifying the source code.

**Comment by awels** [comment]
Okay cool, then I will probably just create a binary in that project that uses this as a library.

**Comment by awels** [comment]
So a small update, I did manage to create a binary that uses straight up socket to communicate, and the project I am integrating with uses stunnel to provide the TLS capability for the socket application. The implementation was relatively straight forward. Thanks again for this project!
