### ISSUE TITLE
Mounting the backup?

### ISSUE THREAD

**Issue by jluttine** [dop251/diskrsync#4]
What is the format of the backup file? I ran `sudo diskrsync /dev/sdb1 ~/usbstick/stick.img`. Is the target file some kind of image file that can be mounted?

Motivation: I backup my encrypted disk to a remote location. I would like to be able to access that backup file from yet another computer. I've done this with sshfs+losetup+cryptsetup. In that case the image file contains LUKS encrypted filesystem. I'm wondering if something similar could be done with the resulting backup file with diskrsync (assuming the original source device was LUKS encrypted block device):

```
# Mount remote over SSH
sshfs $REMOTE $IMAGEDIR

# Use loop device to access the image file as a file system
losetup $LOOPDEVICE $IMAGEDIR/$IMAGEFILE

# Decrypt the encrypted file system
cryptsetup luksOpen $LOOPDEVICE $MAPPER

# Mount the decrypted file system
mount /dev/mapper/$MAPPER $MOUNTDIR
```

I'll play around and see if I can make it work, but I would like to hear if you have the answer.

**Comment by jluttine** [comment]
Well, yes, that seems to work perfectly! This is awesome.

If you know any caveats in this approach, I'd be happy to hear.

I thought I'd ask it here (even if I can make it work) because someone else might also be interested in this.

**Comment by dop251** [comment]
Please be sure to use -no-compress option because if the img file you are copying to does not exist it will be compressed using spgz. You can still access the image using spgz -b, but it does not make sense to compress an encrypted image.

**Comment by jluttine** [comment]
Ok, thanks!
