### ISSUE TITLE
Feature request: rollback versioning

### ISSUE THREAD

**Issue by jluttine** [dop251/diskrsync#5]
Would be great if diskrsync supported versioning so that it is possible to rollback to an old backup. So, whenever the target is updated, the "reverse" of the update diff is stored as a rollback diff. Then these diffs could be applied to the image file in case one wants to rollback the image.

**Comment by dop251** [comment]
It would require a completely new tool I'm afraid, it's not something that can be added as a feature. If you are interested in versioning and rollback I suggest looking at btrfs or zfs snapshots.

**Comment by jluttine** [comment]
Thanks for the response. Not quite sure why it couldn't be added to this tool as a feature. I'll try to rephrase it a bit in case I wasn't clear enough.

After sending the diff to the target, the target first writes a backwards diff which contains the content of those parts that the received diff will overwrite. This "backward diff" is saved to some file. Handling the names of those diff files can be done by the user. And when the user wants to rollback, they just log into the remote machine and apply any "backward diffs" to the image file or block device. Of course, applying diffs incorrectly will corrupt the block device or image file.

So, the call could look something like:
```
diskrsync /dev/sda1 jluttine@domain.com:~/disk.img --diff-file-suffix .diff-20170102 
```

This would write a file `~/disk.img.diff-20170102` on the remote machine. In order to rollback versions, one can apply any diffs on the remote machine:
```
diskrsync --apply-diff-file ~/disk.img.diff-20170102 ~/disk.img
```
This would revert `disk.img` back to the state it was before the syncing above. For simplicity, it would be the user's responsibility to apply diffs in the right order and manage their suffices etc.

But I don't see why this would require a completely new tool. I might be missing something.
