### ISSUE TITLE
Disabling hole punching?

### ISSUE THREAD

**Issue by jluttine** [dop251/diskrsync#7]
Any ideas what's wrong here:

```
# diskrsync --verbose --no-compress /dev/vg-root/lv-root-snap jluttine@domain.com:~/backup.img
2018/01/07 19:13:33 Target failed: operation not supported
2018/01/07 19:13:33 exit status 1
```

I took snapshot of a LV which contains LUKS. I've managed to use diskrsync on another LUKS device directly so I'm wondering is LV somehow breaking compatibility.

**Comment by jluttine** [comment]
Hmm.. I have multiple disks on my computer and thus many partitions that are LUKS encrypted similarly. Some of those work with diskrsync, some not. The one that is the mounted as the root partition `/`, doesn't work. Also, the one that is under LVM, doesn't work. The two others (mounted under `/home` and `/media`) work. Weird.

**Comment by dop251** [comment]
Do you always use the same target? I suspect that when it does not work the target is on a filesystem that does not support punching holes (i.e. not on ext4, xfs, or btrfs).

**Comment by jluttine** [comment]
I use the same target, deleting the target before sync now that i'm testing. I'll check the filesystem. Can I avoid punching holes?

On January 7, 2018 9:33:35 PM GMT+02:00, Dmitry Panov <notifications@github.com> wrote:
>Do you always use the same target? I suspect that when it does not work
>the target is on a filesystem that does not support punching holes
>(i.e. not on ext4, xfs, or btrfs).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dop251/diskrsync/issues/7#issuecomment-355846356

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jluttine** [comment]
The filesystem seems to be `nfs4`.

**Comment by jluttine** [comment]
And when I say it worked for some device, I just let it sync a few megabytes, because syncing the whole 300GB device would take days and I'm not planning to sync all of those. The device that I'm planning to sync, syncs 144K before the error, so it could be that the working devices would also fail but only after syncing much more data. So I'm not sure whether they are working or not. I did however manage to fully sync a 8GB LUKS encrypted USB stick to that same location.

**Comment by jluttine** [comment]
Just in case it matters: The other failing (non-LVM) LUKS device is different from the other LUKS devices in that the partition table entries are not in disk order (partition ID 4 is first, then ID1, then ID 2). I guess it's just a coincidence that this device fails, but I thought I'd mention just in case.

**Comment by jluttine** [comment]
Yep, one of the "working" devices failed now at 39M. So I would guess that all those devices fail if I just let them run long enough.

**Comment by jluttine** [comment]
So I suppose the issue is hole punching. Can I disable it somehow? Or do I need to write random data to my unsed diskspace? Or, as I'm using LUKS, I suppose I can just write zeros with `zerofree` as that is encrypted to "random" data. But disabling hole punching would easier and more robust.

**Comment by dop251** [comment]
At present it's not possible to avoid punching holes unfortunately. I'm going to change it so that it falls back to writing zeros instead of punching a hole when --no-compress it specified and punching holes is not supported.

**Comment by jluttine** [comment]
That'd be super great. Do you have any idea when you might implement this? (Don't mean to put pressure.)

Also, you don't have any tags/releases. Would you prefer using them or are all commits equally stable? I'm packaging this for a distro, so that's why I'm interested in that.

**Comment by dop251** [comment]
Apologies, did not have much time to look at it earlier. All commits are equally stable. If there are breaking changes they will be mentioned in the commit message. You can (and should) lock to a particular commit id when building for a distro and then keep an eye on the commit history.

**Comment by jluttine** [comment]
Thanks! Unfortunately, that didn't compile:

```
building
github.com/dop251/spgz
golang.org/x/crypto/blake2b
github.com/dop251/diskrsync
github.com/dop251/diskrsync/diskrsync
# github.com/dop251/diskrsync/diskrsync
go/src/github.com/dop251/diskrsync/diskrsync/main.go:211:30: undefined: spgz.NewSparseFileWithFallback
builder for ‘/nix/store/72j6vwwhvki0vvwhw87v2sl7g9biqjsn-diskrsync-unstable-2018-02-03.drv’ failed with exit code 1
error: build of ‘/nix/store/72j6vwwhvki0vvwhw87v2sl7g9biqjsn-diskrsync-unstable-2018-02-03.drv’ failed
```

**Comment by jluttine** [comment]
If the definition of `NewSparseFileWithFallback` was supposed to be included in the commit, it's missing.

**Comment by jluttine** [comment]
Oh, needed to update some dependencies too. Thanks.

**Comment by jluttine** [comment]
I confirm that it seems to work. Previously it crashed during the first few megabytes. Now it has uploaded already 44MB so I think it's going to work. Thanks a lot for fixing this!

**Comment by jeredfloyd** [comment]
This patch does not seem to be sufficient for writing to a Linux block device on the target side; the sync fails on the first holepunch attempt with "no such device".  Forcing "fallback" to true solve the problem.
