### ISSUE TITLE
Dependencies? (other than Go deps)

### ISSUE THREAD

**Issue by jluttine** [dop251/diskrsync#8]
I'm getting the following error when running diskrsync:
```
bash: /...../bin/diskrsync: No such file or directory
2018/04/22 17:45:07 exit status 127
```

It works when the destination is just a local filesystem path, but with remote locations I get this error. It asks my password for the remote location and then raises this error so I think SSH is working. And I do have `ssh` installed. Could I be missing some other dependency? I couldn't find a list of required packages (other than the go dependencies).

**Comment by jluttine** [comment]
It happens both with and without `--no-compress`.

**Comment by jluttine** [comment]
Figured it out. Calling `/path/to/diskrsync` doesn't work if the path is different on the remote machine... Not sure if this is intended behaviour or not.

**Comment by dop251** [comment]
This is how it's implemented now. In most cases you will have the executable available in PATH on both sides, so you would just call it "diskrsync".

rsync has an option to specify the path to the remote command and it would be nice to have it as well. So, PRs are welcome :)
